version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx_dockerfile
      args:
        Project: ${Project}
    depends_on:
      - mysql
      - redis
      - mongo
      - php74
    container_name: nginx
    networks:
      - net
    ports:
      - 9000:80
      - 9001:443
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./${Project}:/usr/share/nginx/html/${Project}
  mysql:
    image: mysql:latest
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - 3306:3306
    networks:
      - net
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - net
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - net
  php74:
    build:
      context: .
      dockerfile: php_dockerfile
      args:
        Project: ${Project}
        Project_URL: ${Project_URL}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DB: ${MYSQL_DB}
    depends_on:
      - mysql
      - redis
      - mongo
    container_name: php74
    networks:
      - net
    volumes:
      - ./${Project}:/var/www/html
    
networks:
  net:
    external: true

